### PR TITLE
Feature/internal test parallelization

### PR DESCRIPTION
**Pull request by ljubon**
Build test job should have default environment variables for master/tags and schedule events, otherwise use `ILGPU_CLEAN_TESTS=false` and `ILGPU_TEST_PARALLELIZATION_LEVEL=4` to debug and test parallelization.

Example:
 [here ](https://github.com/ljubon/ILGPU/runs/4831531492?check_suite_focus=true#step:7:3)is when the condition is `true` (p.s I've changed just `if condition` to match my branch name) and [here ](https://github.com/ljubon/ILGPU/runs/4831531659?check_suite_focus=true#step:8:7)confirmation that jobs `Build and test` afterward used configured values.

Update: moved [official PR](https://github.com/m4rs-mt/ILGPU/pull/712) to ready for review

### CODE REVIEW

**Comment by pavlovic-ivan** [comment]
@ljubon changes look good. Can you also provide a link to a working workflow, with CUDA tests executed, and this change applied?

**Comment by ljubon** [comment]
> @ljubon changes look good. Can you also provide a link to a working workflow, with CUDA tests executed, and this change applied?

sure, [here ](https://github.com/ljubon/ILGPU/runs/4831531492?check_suite_focus=true#step:7:3)is when the condition is `true` (p.s I've changed just `if condition` to match my branch name) and [here ](https://github.com/ljubon/ILGPU/runs/4831531659?check_suite_focus=true#step:8:7)confirmation that jobs `Build and test` afterward used configured values.

**Comment by pavlovic-ivan** [comment]
@ljubon cool, thanks! 🥇

**Review by pavlovic-ivan — APPROVED** [review]

**Review by mkomatinovic — APPROVED** [review]

**Comment by ljubon** [comment]
new changes are pushed, please check when you can 🙏  @pavlovic-ivan @mkomatinovic @mhadzic 

[here ](https://github.com/ljubon/ILGPU/runs/4900300216?check_suite_focus=true#step:7:4)is test workflow and [values ](https://github.com/ljubon/ILGPU/runs/4900300216?check_suite_focus=true#step:8:7)in build job

**Comment by pavlovic-ivan** [comment]
@ljubon Approved 🚀

**Review by pavlovic-ivan — APPROVED** [review]

**Pull request merged**
